### ISSUE TITLE
当我使用你给的grpc示例时发生了下面这个错误

### ISSUE THREAD

**Issue by Hedgehogcat** [catcherwong-archive/2019#1]
![H254X5(SF6JYW7QGQ{WXG07](https://user-images.githubusercontent.com/24996486/62819659-9d45f780-bb8a-11e9-8531-a5beefe8cc88.png)

**Comment by Hedgehogcat** [comment]
http2 是否需要做配置？

**Comment by Hedgehogcat** [comment]
![4CJ2UU_7~QV6$} IMRE6`YE](https://user-images.githubusercontent.com/24996486/62819705-586e9080-bb8b-11e9-85e4-83da19adf724.png)
不管我使用上面或是下面这种方式都会得到第一张图的提示信息

**Comment by catcherwong** [comment]
@Hedgehogcat 

要注意一点，在server端，启动的一定是HTTPS的！！这个很重要。

我看到你上面的截图，是HTTP的，你可能需要改一下  `launchSettings.json`

**Comment by Hedgehogcat** [comment]
对，正是因为不可信，所以我在启动 grpc时候直接就报错了。
![image](https://user-images.githubusercontent.com/24996486/62842910-5d952200-bce8-11e9-8e41-061bc08fa816.png)
而我按照提示 运行
![image](https://user-images.githubusercontent.com/24996486/62842917-743b7900-bce8-11e9-91ec-5d23cd227d3a.png)
再次启动项目还是会出现第一个截图里面的错误，是否是因为每一次启动都生成了一个新的证书还是说需要配置某些东西？我的grpc配置如下 
![image](https://user-images.githubusercontent.com/24996486/62842932-97febf00-bce8-11e9-91a7-76446bc73ce9.png)
![image](https://user-images.githubusercontent.com/24996486/62842938-9df4a000-bce8-11e9-8da6-170ed1715daa.png)

**Comment by catcherwong** [comment]
那个生成的https证书应该是全局通用的，不会每都都生成。

看上去配置文件也没有问题。

我也看不出为什么不行 😂

**Comment by Hedgehogcat** [comment]
我找到解决办法了。1，删除所有localhost证书，2.进入程序目录（必须）使用命令donet dev-certs https --trust 安装并信赖证书，3.运行程序 就可以使用https了。但是还是出现了下面这错误
![image](https://user-images.githubusercontent.com/24996486/63139678-ba0e7f00-c011-11e9-99d2-4d7ef60d1cb3.png)


![(3@4`ZIZM1~F((Z(V5}RZ`U](https://user-images.githubusercontent.com/24996486/63139742-f04bfe80-c011-11e9-853c-f503d9496d41.png)

**Comment by Hedgehogcat** [comment]
安装版本的问题，nuget重新安装一下就搞定了。
