### ISSUE TITLE
注册出错无法启动

### ISSUE THREAD

**Issue by wf270906853** [catcherwong-archive/2019#2]
![image](https://user-images.githubusercontent.com/22044679/64587057-b41d7b00-d3d0-11e9-8370-f0a9e17ff159.png)

**Comment by catcherwong** [comment]
可以尝试直接 `dotnet run` 来运行。

**Comment by catcherwong** [comment]
如果想从VS里面进行调试代码的话，建议不要用IIS Express启动调试，如下图所示，选择具体的项目。

![a](https://user-images.githubusercontent.com/8394988/64627046-8ad90b00-d421-11e9-8dc8-c2c58aafff0f.png)

**Comment by wf270906853** [comment]
能给说明一下。为什么IIS会有问题？SKD是不是存在这个BUG？

**Comment by catcherwong** [comment]
目前 `Nacos.AspNetCore` 用的是 `IServerAddressesFeature` 来获取当前机器启动的url，主要是用来获取IP地址和端口这两个信息。

https://github.com/catcherwong/nacos-sdk-csharp/blob/675b3092cdf7cb489f5e9dd40de7de63037da8ea/src/Nacos.AspNetCore/ServiceCollectionExtensions.cs#L38-L48

你这个报错的原因就是 获取到的 `addresses` 为空，至于原因，看一下这个Issue就大概知道了。

https://github.com/aspnet/AspNetCore/issues/8218
